# Generated by Django 5.2.12 on 2026-03-20 23:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("is_available", models.BooleanField(default=False)),
                ("max_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("min_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("service_radius_km", models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ("bio", models.TextField(blank=True, default="")),
                ("rating", models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ("total_ratings", models.PositiveIntegerField(default=0)),
                (
                    "agent_type",
                    models.CharField(
                        choices=[("certified", "Certified"), ("self_enrolled", "Self Enrolled")],
                        default="self_enrolled",
                        max_length=15,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["is_available"], name="agents_agen_is_avai_a6e69c_idx"),
                    models.Index(fields=["latitude", "longitude"], name="agents_agen_latitud_ed4122_idx"),
                ],
            },
        ),
    ]
