# Generated by Django 5.2.3 on 2026-03-14 00:50

import django.db.models.deletion
import project.apps.files.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileAsset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, max_length=500, upload_to=project.apps.files.models.file_asset_upload_to
                    ),
                ),
                ("storage_path", models.CharField(blank=True, max_length=500)),
                ("storage_bucket", models.CharField(blank=True, max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("profile_picture", "Profile picture"),
                            ("passport", "Passport"),
                            ("document", "Document"),
                            ("other", "Other"),
                        ],
                        default="document",
                        max_length=32,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("authenticated", "Authenticated users")],
                        default="private",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                        ],
                        default="uploading",
                        max_length=16,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_file_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_file_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_file_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["owner", "created_at"], name="files_filea_owner_i_879b6c_idx"),
                    models.Index(fields=["visibility", "status"], name="files_filea_visibil_794e03_idx"),
                    models.Index(fields=["kind", "status"], name="files_filea_kind_6caf97_idx"),
                ],
            },
        ),
    ]
