# Generated by Django 5.2.12 on 2026-03-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileasset",
            name="kind",
            field=models.CharField(
                choices=[
                    ("profile_picture", "Profile picture"),
                    ("passport", "Passport"),
                    ("document", "Document"),
                    ("selfie", "Selfie"),
                    ("other", "Other"),
                ],
                default="document",
                max_length=32,
            ),
        ),
    ]
