# Generated by Django 5.2.12 on 2026-09-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_add_selfie_file_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileasset",
            name="kind",
            field=models.CharField(
                choices=[
                    ("profile_picture", "Profile picture"),
                    ("passport", "Passport"),
                    ("ghana_card", "Ghana Card"),
                    ("document", "Document"),
                    ("selfie", "Selfie"),
                    ("other", "Other"),
                ],
                default="document",
                max_length=32,
            ),
        ),
    ]
