# Generated by Django 5.2.12 on 2026-03-22 22:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0002_certificationapplication"),
        ("wallets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhysicalTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(choices=[("cash_out", "Cash Out"), ("deposit", "Deposit")], max_length=10),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("network", models.CharField(max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("verification_code", models.CharField(blank=True, default="", max_length=6)),
                ("meeting_latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("meeting_longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("meeting_description", models.TextField(blank=True, default="")),
                ("user_confirmed", models.BooleanField(default=False)),
                ("agent_confirmed", models.BooleanField(default=False)),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="physical_transactions",
                        to="agents.agentprofile",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="physical_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="physical_transactions",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="transaction_status_c8affe_idx"),
                    models.Index(fields=["user", "status"], name="transaction_user_id_0e0c55_idx"),
                    models.Index(fields=["agent", "status"], name="transaction_agent_i_bfc857_idx"),
                ],
            },
        ),
    ]
