# Generated by Django 5.2.12 on 2026-03-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="paystack_recipient_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="wallet",
            name="paystack_subaccount_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
