# Generated by Django 5.2.12 on 2026-09-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0005_make_wallet_phone_unique_per_user_again"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="is_signup_wallet",
            field=models.BooleanField(default=False),
        ),
    ]
