# Generated by Django 5.2.12 on 2026-03-23 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0002_certificationapplication"),
        ("wallets", "0002_add_paystack_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Interest rate as a percentage (e.g. 10.00 = 10%)",
                        max_digits=5,
                    ),
                ),
                (
                    "total_repayment",
                    models.DecimalField(
                        decimal_places=2, help_text="amount + interest, computed at approval time", max_digits=10
                    ),
                ),
                ("penalty_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("outstanding_balance", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("disbursing", "Disbursing"),
                            ("active", "Active"),
                            ("repaying", "Repaying"),
                            ("completed", "Completed"),
                            ("defaulted", "Defaulted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("network", models.CharField(max_length=15)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("disbursed_at", models.DateTimeField(blank=True, null=True)),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
                ("last_penalty_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("defaulted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="loans", to="agents.agentprofile"
                    ),
                ),
                (
                    "agent_wallet",
                    models.ForeignKey(
                        blank=True,
                        help_text="The agent's wallet used for funding and receiving repayment",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans_funded",
                        to="wallets.wallet",
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans_as_borrower",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "borrower_wallet",
                    models.ForeignKey(
                        help_text="The wallet that receives the disbursement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans_received",
                        to="wallets.wallet",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LoanPayment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("disbursement", "Disbursement"), ("repayment", "Repayment")], max_length=15
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("success", "Success"), ("failed", "Failed")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "reference",
                    models.CharField(help_text="Our internal reference sent to Paystack", max_length=100, unique=True),
                ),
                (
                    "paystack_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Paystack's own reference returned in response",
                        max_length=100,
                    ),
                ),
                ("payer_phone", models.CharField(max_length=15)),
                ("payer_network", models.CharField(max_length=15)),
                ("recipient_subaccount", models.CharField(blank=True, default="", max_length=50)),
                ("paystack_response", models.JSONField(blank=True, default=dict)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="loans.loan"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["status", "created_at"], name="loans_loan_status_59a4c3_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["borrower", "status"], name="loans_loan_borrowe_d07c9e_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["agent", "status"], name="loans_loan_agent_i_9f9409_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["deadline_at"], name="loans_loan_deadlin_c1fe2c_idx"),
        ),
        migrations.AddIndex(
            model_name="loanpayment",
            index=models.Index(fields=["reference"], name="loans_loanp_referen_9ef773_idx"),
        ),
        migrations.AddIndex(
            model_name="loanpayment",
            index=models.Index(fields=["loan", "payment_type"], name="loans_loanp_loan_id_e52f0b_idx"),
        ),
    ]
