# Generated by Django 5.2.12 on 2026-03-24 15:04

from decimal import Decimal

from django.db import migrations, models


def backfill_loan_fee_fields(apps, schema_editor):
    Loan = apps.get_model("loans", "Loan")
    LoanPayment = apps.get_model("loans", "LoanPayment")

    for loan in Loan.objects.all().iterator():
        total_interest = max(
            Decimal(loan.total_repayment) - Decimal(loan.amount) - Decimal(loan.penalty_amount), Decimal("0.00")
        )
        loan.agent_interest_amount = total_interest
        loan.agent_receivable_balance = Decimal(loan.outstanding_balance)
        loan.save(update_fields=["agent_interest_amount", "agent_receivable_balance"])

    for payment in LoanPayment.objects.all().iterator():
        payment.charge_amount = Decimal(payment.amount)
        payment.transfer_amount = Decimal(payment.amount)
        payment.save(update_fields=["charge_amount", "transfer_amount"])


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_rename_loanpayment_recipient_subaccount_loanpayment_recipient_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="agent_interest_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="loan",
            name="agent_receivable_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="loan",
            name="origination_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="loan",
            name="platform_interest_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="loanpayment",
            name="charge_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="loanpayment",
            name="platform_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="loanpayment",
            name="transfer_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="loanpayment",
            name="amount",
            field=models.DecimalField(decimal_places=2, help_text="Amount applied to the loan ledger", max_digits=10),
        ),
        migrations.RunPython(backfill_loan_fee_fields, migrations.RunPython.noop),
    ]
