# Generated by Django 5.2.12 on 2026-03-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agent_status",
            field=models.CharField(
                choices=[("none", "None"), ("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(choices=[("user", "User"), ("agent", "Agent")], default="user", max_length=10),
        ),
    ]
