# Generated by Django 5.2.3 on 2026-03-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="supabase_user_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
