# Generated by Django 5.2.12 on 2026-03-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_role_and_agent_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kyc_status",
            field=models.CharField(
                choices=[("none", "None"), ("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="none",
                max_length=10,
            ),
        ),
    ]
