# Generated by Django 5.2.3 on 2026-07-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0005_loanguarantor")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
