# Generated by Django 5.2.12 on 2026-09-14 17:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_alter_fileasset_kind"),
        ("kyc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="kycsubmission",
            name="ghana_card_number",
            field=models.CharField(blank=True, db_index=True, max_length=15),
        ),
        migrations.AddField(
            model_name="kycsubmission",
            name="verification_method",
            field=models.CharField(
                choices=[("manual_review", "Manual review"), ("ghana_card_registry", "Ghana Card registry")],
                default="manual_review",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="kycsubmission",
            name="id_type",
            field=models.CharField(choices=[("national_id", "Ghana Card")], max_length=20),
        ),
        migrations.CreateModel(
            name="GhanaCardRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("card_number", models.CharField(max_length=15, unique=True)),
                ("first_names", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("sex", models.CharField(blank=True, max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "card_back",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ghana_card_back_records",
                        to="files.fileasset",
                    ),
                ),
                (
                    "card_front",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ghana_card_front_records",
                        to="files.fileasset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ghana_card_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["is_active", "card_number"], name="kyc_ghanaca_is_acti_ee9233_idx"),
                    models.Index(fields=["surname", "first_names"], name="kyc_ghanaca_surname_443aae_idx"),
                ],
            },
        ),
    ]
