# Generated by Django 5.2.12 on 2026-09-14 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_alter_fileasset_kind"),
        ("kyc", "0002_kycsubmission_ghana_card_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="kycsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "approved"), models.Q(("ghana_card_number", ""), _negated=True)),
                fields=("ghana_card_number",),
                name="unique_approved_ghana_card",
            ),
        ),
    ]
